version: "3"

services:
  # learning-capsules-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile  
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   command: npm start  
  learning-capsules-db:
    image: postgres:15
    restart: always
    container_name: db-learning-capsule
    environment:
      POSTGRES_DB: learning_capsule
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"